### ISSUE TITLE
[dns] Unit tests can pick an in-use port for test http server

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#720]
And once they have, it happens on every run as the golang random number generator isn't being explicitly seeded. Perhaps it would be better to let the kernel pick an actually unused number (not sure if golang exposes this capability) or to loop until we bind successfully.

**Comment by inercia** [comment]
This is solved in #615 (in [this code](https://github.com/inercia/weave/commit/a0ddde21c523ab44ff58780281d038b9eb612cdd#diff-7d7cca87c8b1140efab81f1f58b9c0edR175) for binding)

**Comment by inercia** [comment]
Fixed in #761

**Comment by awh** [comment]
It's not fixed, that's why I didn't close it in the merge commit message:

https://github.com/weaveworks/weave/blob/master/nameserver/http_test.go#L38

**Comment by inercia** [comment]
Oh, sorry, I've just realized this issue was about the HTTP port, not the DNS port...

**Comment by rade** [comment]
issue also applies to ipam tests.
